---

- hosts: test
  user: ubuntu
  roles:
    - common
    - repos
    - statsd
  vars:
     app_name: "chacra"
     use_ssl: true
     wsgi_file: wsgi.py
     wsgi_callable: application
     ansible_ssh_port: 22
     binary_root: "/opt/binaries"
     repos_root: "/opt/repos"
     git_chacra: "https://github.com/sine-cloud/chacra"
     branch: "main"
     development_server: true
     purge_repos: True
     fqdn: "{{ inventory_hostname }}"
     ## required. use something like chacra# so rabbitmq will start
     ## see http://tracker.ceph.com/issues/19316
     # short_hostname: "chacra#"
     # required for first deploy
     # api_user: "admin"
     # api_key: "secret"
     # graphite reporting for statsd
     graphite_host: "shaman.sinecloud.com"
     ## required
     # graphite_api_key: '1234-asdf-1234'
     # callbacks
     callback_url: "https://shaman.sinecloud.com/api/repos/"
     ## required for first deploy
     # callback_user: "admin"
     # callback_key: "secret"
     callback_verify_ssl: False
     health_ping: true
     health_ping_url: "https://shaman.sinecloud.com/api/nodes/"
     use_letsencrypt: False
     #nginx_ssl_cert_path: "/etc/letsencrypt/live/{{ fqdn }}/fullchain.pem"
     nginx_ssl_cert_path: "/etc/ssl/certs/{{ fqdn }}-bundled.crt"
     #nginx_ssl_key_path: "/etc/letsencrypt/live/{{ fqdn }}/privkey.pem"
     nginx_ssl_key_path: "/etc/ssl/private/{{ fqdn }}.key"
     combine_deb_repos: False
     git_statsd: "https://github.com/sine-cloud/statsd"
